# docker run --name chat-psql -e POSTGRES_PASSWORD=password  -d postgres
version: '3.1'

services:

  chat-psql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
